# This is a complete configuration to deploy Loki backed by the filesystem.
# The index will be shipped to the storage via tsdb-shipper.

auth_enabled: false

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

limits_config:
  ingestion_rate_mb: 15
  ingestion_burst_size_mb: 30
  per_stream_rate_limit: 10MB
  per_stream_rate_limit_burst: 20MB
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 744h
  max_query_length: 0h

storage_config:
  filesystem:
    directory: /tmp/loki/chunks

schema_config:
  configs:
    - from: 2024-04-01
      object_store: s3
      store: tsdb
      schema: v13
      index:
        prefix: index_
        period: 24h
        
# storage_config:
#   boltdb_shipper:
#     active_index_directory: /loki/boltdb-shipper-active
#     cache_location: /loki/boltdb-shipper-cache
#     cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
#     shared_store: filesystem
#   filesystem:
#     directory: /loki/chunks

# compactor:
#   working_directory: /loki/boltdb-shipper-compactor
#   shared_store: filesystem

# chunk_store_config:
#   max_look_back_period: 336h # how far data can be queried

# table_manager:
#   retention_deletes_enabled: true
#   retention_period: 336h # how long data remaind

# ruler:
#   storage:
#     type: local
#     local:
#       directory: /loki/rules
#   rule_path: /loki/rules-temp
#   alertmanager_url: http://alertmanager:9093
#   ring:
#     kvstore:
#       store: inmemory
#   enable_api: true